server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/customer/**
        - id: fraud
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/fraud/**
        - id: notification
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/notification/**
management:
  tracing:
    sampling:
      probability: 1.0